### ISSUE TITLE
postman return error on create new User  

### ISSUE THREAD

**Issue by k2gsalem** [joselfonseca/laravel-api#64]
on creating a new user with the role return 500 Internal Server Error with
"message": "Return value of App\Entities\User::getStoredRole() must implement interface Spatie\Permission\Contracts\Role, null returned",
how to solve this issue

**Comment by kslimani** [comment]
Looking at [current source code](https://github.com/joselfonseca/laravel-api/blob/master/app/Support/HasRolesUuid.php#L18) this may happen when retrieving role with non-existing name or uuid.

And also looking at laravel-permission [current source code](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L175) this *may* be due to `insteadof` directive  in current [User entity class](https://github.com/joselfonseca/laravel-api/blob/master/app/Entities/User.php#L19).

@joselfonseca what do you think ?

**Comment by joselfonseca** [comment]
seems like it, I haven't use this in a while since we moved to GraphQL but yeah If you are able to fix it that would be nice, if not i'll find some time.

**Comment by k2gsalem** [comment]
I changed the default Guard web to api and hide web in auth.php. no issue now 
  'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

  'guards' => [
        // 'web' => [
        //     'driver' => 'session',
        //     'provider' => 'users',
        // ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],
